version: "3.8"
services:
 elasticsearch:
  container_name: elasticsearch
  image: elasticsearch:7.17.5
  restart: unless-stopped
  networks:
  - link
  ports:
  - 9200:9200
  - 9300:9300
  environment:
  - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  - bootstrap.memory_lock=true
  - discovery.type=single-node
  volumes:
  - ./bind/data:/usr/share/elasticsearch/data
  - ./bind/plugins:/usr/share/elasticsearch/plugins
  - ./bind/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  - /etc/localtime:/etc/localtime:ro
  logging:
   driver: "json-file"
   options:
    max-size: "1m"

networks:
 link:
  external: true
